name = "rh-interiors"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "woodtong"
database_id = "97fee977-cfe3-4542-93c8-199eb427d347"

compatibility_flags = [ "nodejs_compat" ]