name = "rh-interiors"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "rh-interiors-db"
database_id = "tu-id-de-base-de-datos-aqui"
